src/main/kotlin/api.kt, src/main/kotlin/implementation.kt
Looks like we don't need builder here anymore, calls like
`TeamCityInstance.builder("http://teamcity.jetbrains.com").build().builds(...)`
contains word 'build' too many times.
=> simplification: get rid of builder for TeamCityInstance

src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt, src/test/kotlin/org.jetbrains.teamcity.rest/BranchesTest.kt, src/test/kotlin/org.jetbrains.teamcity.rest/BuildTest.kt
Provide API for fetching version control revisions checked out in corresponding build.
No additional http requests made in implementation to obtain revisions data, the request made by  `build(...)` method already receives that data though it's not parsed.
=> Support build revisions fetching 

.travis.yml, build.gradle
Upgrade to Kotlin 1.1.2-2 (the latest version for now)
It may cause problems if the library is being used in projects with older versions of Kotlin. I have no such examples in mind, so, maybe it's worth upgrading
=> kotlin 1.1

src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt
This header helps to avoid returning xml in response and then facing exception like [here](https://stackoverflow.com/questions/26290267/retrofit-removing-some-invalid-characters-from-response-body-before-parsing-it)
=> add "Accept: application/json" header to all requests

src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt, src/test/kotlin/org.jetbrains.teamcity.rest/BuildTest.kt
Artifact path was incorrectly encoded, which resulted into URL like
`https://teamcity.jetbrains.com/guestAuth/app/rest/builds/id:1111311/artifacts/children/maven%2Forg` 
which results into HTTP 400 error, instead of correct URL
`https://teamcity.jetbrains.com/guestAuth/app/rest/builds/id:1111311/artifacts/children/maven/org`
=> Fix invalid artifacts path - it should not be encoded

teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/VcsRootTest.kt
Hi guys,
this PR contributes the following two changes:
- Commit `Replace VcsRoot with VcsRootInstance in Revision`
The previously implemented `Revision` contained a `VcsRoot` having the field `id` holding a `VcsRootId`. This `id` was then filled with the value hold by the `id` attribute of the `vcs-root-instance` element (see an example xml below). This `id` however refers to an instance of a `VcsRoot` and not a `VcsRoot` itself. Thus, trying to access the vcs root under `/app/rest/vcs-roots/id:{id}` will not work.
This commit replaces the `VcsRoot` of a `Revision` with a `VcsRootInstance` having the value of the attribute `vcs-root-id` of the element `vcs-root-instance` as the `VcsRootId`.
```xml
...
<revisions count="1">
<revision version="96bf990187e26d5637f1db8a820c1ed55b02b484" …
```
=> Vcs properties

teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/VcsRootTest.kt
Hi guys,
this PR refers to the suggestion of @chashnikov from PR GH-37 and contributes the following two changes:
- Commit `VcsRootProperty value could be null` 9db5c95
The value of a property of a `VcsRoot` may be null (e.g. `secure:password` of the following xml section).
```xml
...
<properties count="12">
<property name="agentCleanFilesPolicy" value="ALL_UNTRACKED"/>
<property name="agentCleanPolicy" value="ON_BRANCH_CHANGE"/>
<property name="authMethod" value="PASSWORD"/>
<property name="branch" value="refs/heads/master"/>
<property name="ignoreKnownHosts" value="true"/>
<property name="secure:password"/>
<property name="submoduleCheckout" value="CHECKOUT"/>
<property name="teamcity:branchSpec" value="refs/heads/*"/>
<property name="url" …
```
=> Vcs properties accessors

teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/BuildTest.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/testUtils.kt
Currently, pagination is implemented using `count`. While in general, this approach works, there are some corner cases when it leads to an infinite loop. From [TeamCity documentation](https://confluence.jetbrains.com/display/TCD18/REST+API):
>Even when the returned "count" is 0, it does not mean there are no more items if there is "nextHref" attribute present.
The suggested approach relies on TeamCity and uses only `nextHref` to perform pagination.
=> Implement pagination using nextHref

build.gradle, teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/BuildTest.kt
This is useful for Eclipse Kotlin plugin Ant to Gradle rewrite.
Notes:
1. Is there a better way to assert the exception message than the one in unit test?
2. Is this API change backwards compatible in Kotlin?
- If so, do we care about not breaking Java clients?
- The method called from Java will now contain 3 parameters which is API breaking change from Java's perspective.
=> Adding support for finding artifact recursively

teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/BuildTest.kt
This commit adds an untilDate field in BuildLocator.
Fixes https://github.com/JetBrains/teamcity-rest-client/issues/51
=> Support untilDate in BuildLocator

teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt
Several small improvements:
* Do not include OutputStream in debug log message for `downloadArtifact`
* Ensure final message after the download is not lost
* Remove target download file of download failed
=> downloadArtifact cleanup

build.gradle, gradle/wrapper/gradle-wrapper.properties, teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/ShutdownTest.kt
update Kotlin to 1.3.61, simplify Gradle script
OkHttp4 is binary compatible to OkHttp3, the update does not require
changing other dependencies and Retrofit
=> fix JDK11 warning from older OkHttp3, use OkHttp4

teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt
Added support to list all test runs with all the invocations flattened
GET http://teamcity:8111/app/rest/testOccurrences?locator=build:(id:XXX),test:(id:XXX),expandInvocations:true
=> added possibility to ask for expanded invocations of testruns

CHANGELOG.md, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt
Fix not passing agentId param in deprecated `BuildConfiguration::runBuild` method overload.
=> Fix not passing agentId param in runBuild

gradle.properties, teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt
Minimal support to deal with detached builds:
* detachedFromAgent property.
* finish() method.
=> Minimal support for detached builds

CHANGELOG.md, gradle.properties, teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt
We can observe OOM due to the large number of red tests in the build. This happens because tests are requested with the `details` field, which can contain large text.
=> Add ability to fetch test occurrence without 'details' field

teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/rest.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/MuteTest.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/TestsTest.kt
We miss support if the mutes in the API. This PR adds support for requesting mutes and getting necessary information.
Our use-case would be to use these API calls to gather mutes from the TC and process them, including adding comments into the project code, in case test gets disabled there.
Tested by replacing `publicInstance` with the TC instance with token auth.
See [RIDER-90544](https://youtrack.jetbrains.com/issue/RIDER-90544).
=> Add support for the Mutes

teamcity-rest-client-api/src/main/kotlin/org/jetbrains/teamcity/rest/api.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/implementation.kt
Use case: we want to filter all failed tests from a project.
=> Add "affectedProject:(id:X)" build locator

teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/coroutines/rest.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/BuildTest.kt
When data is paged, `nextHref` returned by TeamCity server is not encoded.
Previously, teamcity-rest-client was mistakenly configured to send value without encoding. This PR fixes the behavior and introduces a test
=> Paging implementation: fix nextHref encoding

teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/builder.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/coroutines/implementation.kt, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/coroutines/nodePinning.kt
Usage example:
```
import org.jetbrains.teamcity.rest.BuildId
import org.jetbrains.teamcity.rest.TeamCityInstanceBuilder;
val tc = TeamCityInstanceBuilder("https://<multi-node-server>")
.bindToNode("secondary-node")
.withTokenAuth("<token>")
.build()
```
=> Add ability to bind requests to a specific node in a multi-node TeamCity setup

.teamcity/settings.kts, build.gradle, teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/coroutines/implementation.kt, teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/BuildAgentTest.kt
retorofit 2.9.0 -> 2.11.0
okhttp 4.10.0 -> 4.12.0
slf4j-api 1.7.12 -> 2.0.16
=> Update dependency versions
